version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
      # - ./nginx.conf:/etc/nginx/nginx.conf # ถ้าคุณมีไฟล์การตั้งค่าปรับแต่ง
    restart: unless-stopped
